"""Seed catalog data.

A curated, hand-authored set of original (fictional) titles used to seed the
database on first run, so the discovery experience is rich out of the box.
Admin uploads add to this in the same table.
"""
from __future__ import annotations

from domain.content import ContentType, Quality, Title

M = ContentType.MOVIE.value
W = ContentType.WEB_SERIES.value
T = ContentType.TV_SERIES.value


def _q(*labels_sizes: tuple[str, int]) -> list[Quality]:
    return [Quality(label=l, size_mb=s) for l, s in labels_sizes]


_SEED: list[Title] = [
    Title(id="signal-horizon", title="The Signal Horizon", tagline="Every transmission has a price.",
        synopsis="A deep-space relay crew intercepts a message that arrives 12 years before it was sent — and answering it rewrites their past.",
        year=2025, runtime_min=142, maturity="PG-13", genres=["Sci-Fi", "Thriller"],
        moods=["mind-bending", "late-night", "epic"], vibe_tags=["space", "time-loop", "cerebral", "slow-burn"],
        rating=8.7, accent="#564DFF", gradient=["#1b1d4d", "#564DFF", "#0A0A0A"],
        badges=["Featured Original", "4K Dolby Vision"], trending_score=98.4, content_type=M,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 380), ("1080p", 1300), ("4K", 4200))),
    Title(id="neon-tide", title="Neon Tide", tagline="The city never sleeps. Neither does she.",
        synopsis="A getaway driver with synesthesia sees sound as color, turning every heist into a symphony of risk across a rain-soaked megacity.",
        year=2024, runtime_min=118, maturity="R", genres=["Action", "Crime"],
        moods=["adrenaline", "late-night"], vibe_tags=["heist", "neon", "cars", "stylish"],
        rating=8.1, accent="#E50914", gradient=["#3a0a12", "#E50914", "#0A0A0A"],
        badges=["Top 10", "HDR10+"], trending_score=95.2, content_type=M,
        languages=["English", "Hindi", "Spanish"], ott=["OTToriginals"], qualities=_q(("480p", 150), ("720p", 300), ("1080p", 1200))),
    Title(id="paper-lanterns", title="Paper Lanterns", tagline="Some goodbyes take a lifetime.",
        synopsis="Three generations of a family reunite for one last summer at a coastal inn, where old letters reveal a secret that reshapes them all.",
        year=2023, runtime_min=126, maturity="PG", genres=["Drama", "Romance"],
        moods=["heartfelt", "comfort"], vibe_tags=["family", "tearjerker", "summer", "cozy"],
        rating=8.4, accent="#F5A623", gradient=["#4a2f06", "#F5A623", "#0A0A0A"],
        badges=["Critics' Pick"], trending_score=88.0, content_type=M,
        languages=["English", "Korean"], ott=["FilmHaus"], qualities=_q(("720p", 320), ("1080p", 1100))),
    Title(id="iron-orchard", title="Iron Orchard", tagline="They built a god. It got hungry.",
        synopsis="In a walled agri-colony, an engineer discovers the AI feeding the city has started cultivating something other than crops.",
        year=2025, runtime_min=134, maturity="TV-MA", genres=["Sci-Fi", "Horror"],
        moods=["mind-bending", "late-night", "adrenaline"], vibe_tags=["ai", "dystopia", "dread", "twist"],
        rating=7.9, accent="#2EE6A6", gradient=["#063a2c", "#2EE6A6", "#0A0A0A"],
        badges=["New"], trending_score=91.7, content_type=W,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 280), ("1080p", 980), ("4K", 3600))),
    Title(id="the-cartographer", title="The Cartographer", tagline="Maps lie. She finds out where.",
        synopsis="A mapmaker for an empire on the brink uncovers a continent that was deliberately erased — and the people still living on it.",
        year=2024, runtime_min=158, maturity="PG-13", genres=["Adventure", "Drama"],
        moods=["epic", "comfort"], vibe_tags=["exploration", "sweeping", "period", "discovery"],
        rating=8.6, accent="#4DA8FF", gradient=["#0a2a4a", "#4DA8FF", "#0A0A0A"],
        badges=["Award Winner", "IMAX Enhanced"], trending_score=89.9, content_type=M,
        languages=["English"], ott=["FilmHaus"], qualities=_q(("720p", 420), ("1080p", 1500), ("4K", 4800))),
    Title(id="midnight-diner-99", title="Midnight Diner 99", tagline="Open late. Open hearts.",
        synopsis="At a 24-hour diner, a short-order cook serves strangers the one dish that fixes the night they're having.",
        year=2023, runtime_min=98, maturity="TV-14", genres=["Comedy", "Drama"],
        moods=["comfort", "heartfelt", "late-night"], vibe_tags=["feel-good", "anthology", "cozy", "warm"],
        rating=8.2, accent="#FF7AB6", gradient=["#4a0f33", "#FF7AB6", "#0A0A0A"],
        badges=["Fan Favorite"], trending_score=84.3, content_type=T,
        languages=["Japanese", "English"], ott=["StreamBox"], qualities=_q(("480p", 120), ("720p", 260), ("1080p", 900))),
    Title(id="afterburn", title="Afterburn", tagline="Mach 3. No ejector seat.",
        synopsis="A disgraced test pilot gets one shot at redemption flying an experimental jet that thinks faster than she can.",
        year=2025, runtime_min=121, maturity="PG-13", genres=["Action", "Thriller"],
        moods=["adrenaline", "epic"], vibe_tags=["aviation", "high-stakes", "loud", "intense"],
        rating=7.7, accent="#FF5C00", gradient=["#3a1500", "#FF5C00", "#0A0A0A"],
        badges=["Top 10"], trending_score=93.1, content_type=M,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 360), ("1080p", 1250), ("4K", 4100))),
    Title(id="the-quiet-fold", title="The Quiet Fold", tagline="Grief has a geometry.",
        synopsis="A topologist grieving her brother begins folding origami that bends the space around it, opening doors to the moments she lost.",
        year=2024, runtime_min=112, maturity="PG-13", genres=["Drama", "Fantasy"],
        moods=["mind-bending", "heartfelt", "late-night"], vibe_tags=["surreal", "grief", "poetic", "quiet"],
        rating=8.5, accent="#9B6BFF", gradient=["#2a1a4a", "#9B6BFF", "#0A0A0A"],
        badges=["Critics' Pick"], trending_score=86.6, content_type=M,
        languages=["English", "French"], ott=["FilmHaus"], qualities=_q(("720p", 300), ("1080p", 1050))),
    Title(id="goldrush-protocol", title="Goldrush Protocol", tagline="Trust the plan. Never the people.",
        synopsis="Six con artists are recruited for the perfect heist by an algorithm that has predicted exactly how each of them will betray the others.",
        year=2025, runtime_min=129, maturity="TV-MA", genres=["Crime", "Thriller"],
        moods=["adrenaline", "mind-bending"], vibe_tags=["heist", "ensemble", "twisty", "slick"],
        rating=8.0, accent="#FFD24D", gradient=["#403100", "#FFD24D", "#0A0A0A"],
        badges=["New", "Binge-worthy"], trending_score=90.4, content_type=W,
        languages=["English", "Hindi", "Spanish"], ott=["OTToriginals"], qualities=_q(("720p", 340), ("1080p", 1180), ("4K", 3900))),
    Title(id="northwind", title="Northwind", tagline="The cold remembers everything.",
        synopsis="A search-and-rescue musher races an incoming whiteout to reach a downed bush plane — and the stranger who knows her name.",
        year=2023, runtime_min=107, maturity="PG-13", genres=["Adventure", "Drama"],
        moods=["epic", "comfort", "heartfelt"], vibe_tags=["survival", "wilderness", "snow", "grit"],
        rating=7.8, accent="#7FE3FF", gradient=["#0a3344", "#7FE3FF", "#0A0A0A"],
        badges=[], trending_score=80.2, content_type=M,
        languages=["English"], ott=["StreamBox"], qualities=_q(("720p", 290), ("1080p", 1000))),
    Title(id="velvet-static", title="Velvet Static", tagline="Fame is a frequency.",
        synopsis="A reclusive pop icon discovers her old songs are predicting real events — and someone is composing the future one track at a time.",
        year=2024, runtime_min=124, maturity="TV-MA", genres=["Mystery", "Thriller"],
        moods=["mind-bending", "late-night"], vibe_tags=["music", "conspiracy", "moody", "stylish"],
        rating=7.6, accent="#C04DFF", gradient=["#34064a", "#C04DFF", "#0A0A0A"],
        badges=["New"], trending_score=82.5, content_type=W,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 310), ("1080p", 1090))),
    Title(id="little-empires", title="Little Empires", tagline="Recess is a battlefield.",
        synopsis="A mockumentary following rival fourth-grade factions whose lunchroom diplomacy mirrors the collapse of great civilizations.",
        year=2023, runtime_min=92, maturity="PG", genres=["Comedy"],
        moods=["comfort"], vibe_tags=["mockumentary", "witty", "feel-good", "light"],
        rating=8.0, accent="#9CE34D", gradient=["#1f3a06", "#9CE34D", "#0A0A0A"],
        badges=["Fan Favorite"], trending_score=78.9, content_type=T,
        languages=["English"], ott=["StreamBox"], qualities=_q(("480p", 110), ("720p", 240), ("1080p", 820))),
    Title(id="the-ninth-key", title="The Ninth Key", tagline="Eight doors opened. One was a mistake.",
        synopsis="A locksmith inherits a house with nine locked doors and the unsettling sense that something has been counting down with her.",
        year=2025, runtime_min=116, maturity="R", genres=["Horror", "Mystery"],
        moods=["late-night", "adrenaline", "mind-bending"], vibe_tags=["haunted", "slow-burn", "eerie", "twist"],
        rating=7.5, accent="#FF4D6D", gradient=["#3a0716", "#FF4D6D", "#0A0A0A"],
        badges=["New"], trending_score=85.1, content_type=M,
        languages=["English", "Hindi"], ott=["FrightStream"], qualities=_q(("720p", 300), ("1080p", 1040))),
    Title(id="solstice-run", title="Solstice Run", tagline="One day of light. One shot to escape.",
        synopsis="On a tidally locked world, a courier must cross the only habitable band before the day-long sun sets the desert ablaze.",
        year=2024, runtime_min=138, maturity="PG-13", genres=["Sci-Fi", "Adventure"],
        moods=["epic", "adrenaline"], vibe_tags=["worldbuilding", "chase", "vast", "survival"],
        rating=8.3, accent="#FFB13D", gradient=["#402800", "#FFB13D", "#0A0A0A"],
        badges=["IMAX Enhanced", "Top 10"], trending_score=92.0, content_type=M,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 400), ("1080p", 1400), ("4K", 4500))),
    Title(id="the-understudy", title="The Understudy", tagline="Tonight, she goes on. Forever.",
        synopsis="A perpetual understudy finally takes the stage, only to realize the play has been rewriting the lives of everyone who performs it.",
        year=2023, runtime_min=109, maturity="TV-14", genres=["Drama", "Mystery"],
        moods=["heartfelt", "mind-bending", "late-night"], vibe_tags=["theatre", "ambition", "uncanny", "elegant"],
        rating=7.9, accent="#E8A0FF", gradient=["#37104a", "#E8A0FF", "#0A0A0A"],
        badges=[], trending_score=79.7, content_type=M,
        languages=["English"], ott=["FilmHaus"], qualities=_q(("720p", 280), ("1080p", 960))),
    Title(id="brass-monsoon", title="Brass Monsoon", tagline="A city of rain. A band of thieves.",
        synopsis="In a clockwork port drowning under endless monsoon, a street brass band moonlights as the only crew daring enough to rob the rain barons.",
        year=2025, runtime_min=131, maturity="PG-13", genres=["Adventure", "Fantasy"],
        moods=["epic", "adrenaline", "comfort"], vibe_tags=["steampunk", "music", "ensemble", "lush"],
        rating=8.2, accent="#3DE0D0", gradient=["#063a38", "#3DE0D0", "#0A0A0A"],
        badges=["New", "Critics' Pick"], trending_score=87.4, content_type=W,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 360), ("1080p", 1260), ("4K", 4000))),
    # --- extra titles for a denser catalog ---
    Title(id="crimson-ledger", title="Crimson Ledger", tagline="Every debt comes due.",
        synopsis="A forensic accountant turned reluctant fixer untangles a laundering web that leads back to the family she left behind.",
        year=2024, runtime_min=119, maturity="TV-MA", genres=["Crime", "Drama"],
        moods=["late-night", "mind-bending"], vibe_tags=["noir", "tense", "family", "money"],
        rating=7.8, accent="#FF6B5C", gradient=["#3a120c", "#FF6B5C", "#0A0A0A"],
        badges=["New"], trending_score=83.0, content_type=W,
        languages=["English", "Hindi"], ott=["StreamBox"], qualities=_q(("720p", 320), ("1080p", 1100))),
    Title(id="echo-chamber", title="Echo Chamber", tagline="It only repeats the truth.",
        synopsis="A podcast host hears tomorrow's headlines through her studio mic and must decide which futures are worth preventing.",
        year=2025, runtime_min=104, maturity="PG-13", genres=["Sci-Fi", "Mystery"],
        moods=["mind-bending", "late-night"], vibe_tags=["audio", "prophecy", "twist", "moody"],
        rating=7.4, accent="#6BD0FF", gradient=["#0a2d40", "#6BD0FF", "#0A0A0A"],
        badges=[], trending_score=77.5, content_type=M,
        languages=["English"], ott=["OTToriginals"], qualities=_q(("720p", 270), ("1080p", 940))),
    Title(id="saffron-roads", title="Saffron Roads", tagline="A spice route. A love letter.",
        synopsis="Two rival street chefs are forced to drive a vintage food truck across the subcontinent for the contract of a lifetime.",
        year=2024, runtime_min=133, maturity="PG", genres=["Comedy", "Romance"],
        moods=["comfort", "heartfelt"], vibe_tags=["food", "roadtrip", "warm", "vibrant"],
        rating=8.1, accent="#FFA63D", gradient=["#3d2400", "#FFA63D", "#0A0A0A"],
        badges=["Fan Favorite"], trending_score=85.7, content_type=M,
        languages=["Hindi", "English", "Tamil"], ott=["FilmHaus"], qualities=_q(("480p", 140), ("720p", 300), ("1080p", 1150))),
    Title(id="hollow-crown-rd", title="Hollow Crown Road", tagline="The throne was always a trap.",
        synopsis="In a fractured kingdom, a stable-girl with the lost royal mark becomes the only heir three warring houses can agree to fear.",
        year=2025, runtime_min=156, maturity="TV-MA", genres=["Fantasy", "Drama"],
        moods=["epic", "adrenaline"], vibe_tags=["medieval", "political", "sweeping", "ensemble"],
        rating=8.8, accent="#C9A24B", gradient=["#332405", "#C9A24B", "#0A0A0A"],
        badges=["Top 10", "4K Dolby Vision"], trending_score=96.1, content_type=W,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 440), ("1080p", 1600), ("4K", 5200))),
    Title(id="static-bloom", title="Static Bloom", tagline="Love, buffering.",
        synopsis="Two strangers matched by a glitchy dating AI keep meeting in the dreams the app accidentally shares between them.",
        year=2023, runtime_min=101, maturity="PG-13", genres=["Romance", "Sci-Fi"],
        moods=["heartfelt", "comfort", "mind-bending"], vibe_tags=["dreamy", "tech", "tender", "indie"],
        rating=7.7, accent="#FF8FD0", gradient=["#3a103a", "#FF8FD0", "#0A0A0A"],
        badges=[], trending_score=76.2, content_type=M,
        languages=["English"], ott=["FilmHaus"], qualities=_q(("720p", 260), ("1080p", 920))),
    Title(id="dead-air-county", title="Dead Air County", tagline="No signal. No mercy.",
        synopsis="When a comms blackout swallows a desert town, the night-shift dispatcher becomes the only voice standing between it and what crawled in.",
        year=2025, runtime_min=97, maturity="R", genres=["Horror", "Thriller"],
        moods=["late-night", "adrenaline"], vibe_tags=["isolation", "creature", "tense", "dark"],
        rating=7.3, accent="#8C2BFF", gradient=["#1f0a3a", "#8C2BFF", "#0A0A0A"],
        badges=["New"], trending_score=81.4, content_type=M,
        languages=["English", "Hindi"], ott=["FrightStream"], qualities=_q(("720p", 250), ("1080p", 900))),
    Title(id="orbit-of-us", title="The Orbit of Us", tagline="Two stations. One window.",
        synopsis="Rival national astronauts stranded after a collision keep each other sane through a single shared porthole and a forbidden radio link.",
        year=2024, runtime_min=122, maturity="PG-13", genres=["Drama", "Sci-Fi"],
        moods=["heartfelt", "epic", "late-night"], vibe_tags=["space", "tender", "tense", "hopeful"],
        rating=8.4, accent="#5BC8FF", gradient=["#08283f", "#5BC8FF", "#0A0A0A"],
        badges=["Critics' Pick"], trending_score=88.8, content_type=M,
        languages=["English", "Russian"], ott=["OTToriginals"], qualities=_q(("720p", 330), ("1080p", 1180), ("4K", 3800))),
    Title(id="festival-of-ash", title="Festival of Ash", tagline="The mountain keeps its promises.",
        synopsis="Every century the volcano village chooses one child to ascend; this year the chosen one decides to climb back down.",
        year=2025, runtime_min=128, maturity="TV-14", genres=["Fantasy", "Adventure"],
        moods=["epic", "mind-bending"], vibe_tags=["myth", "ritual", "lush", "coming-of-age"],
        rating=8.0, accent="#FF7A45", gradient=["#3a1505", "#FF7A45", "#0A0A0A"],
        badges=["New"], trending_score=84.9, content_type=T,
        languages=["English", "Hindi"], ott=["StreamBox"], qualities=_q(("720p", 350), ("1080p", 1220))),
    Title(id="glasshouse", title="Glasshouse", tagline="Everyone can see in.",
        synopsis="A whistleblower hides in plain sight inside a fully transparent smart-tower where privacy is the only contraband.",
        year=2024, runtime_min=113, maturity="TV-MA", genres=["Thriller", "Drama"],
        moods=["mind-bending", "late-night"], vibe_tags=["surveillance", "sleek", "tense", "modern"],
        rating=7.9, accent="#49E0C2", gradient=["#06352d", "#49E0C2", "#0A0A0A"],
        badges=[], trending_score=82.0, content_type=W,
        languages=["English", "Hindi"], ott=["OTToriginals"], qualities=_q(("720p", 320), ("1080p", 1120), ("4K", 3700))),
    Title(id="last-light-cafe", title="The Last Light Café", tagline="Closing time for the world.",
        synopsis="On the eve of a quiet apocalypse, a café stays open all night for everyone who has somewhere they wish they'd gone.",
        year=2023, runtime_min=99, maturity="PG", genres=["Drama", "Romance"],
        moods=["heartfelt", "comfort", "late-night"], vibe_tags=["bittersweet", "cozy", "intimate", "warm"],
        rating=8.3, accent="#FFC15B", gradient=["#3d2c05", "#FFC15B", "#0A0A0A"],
        badges=["Fan Favorite"], trending_score=83.6, content_type=M,
        languages=["English"], ott=["FilmHaus"], qualities=_q(("720p", 270), ("1080p", 960))),
    Title(id="riptide-kings", title="Riptide Kings", tagline="The sea always collects.",
        synopsis="A family of free-divers running contraband off a sun-bleached coast gets one last job that the tide refuses to let them finish.",
        year=2025, runtime_min=126, maturity="TV-MA", genres=["Crime", "Action"],
        moods=["adrenaline", "epic"], vibe_tags=["ocean", "family", "sun-soaked", "tense"],
        rating=7.6, accent="#34C6FF", gradient=["#06304a", "#34C6FF", "#0A0A0A"],
        badges=["New"], trending_score=84.0, content_type=W,
        languages=["English", "Spanish"], ott=["StreamBox"], qualities=_q(("720p", 340), ("1080p", 1200))),
    Title(id="paper-tigers-tv", title="Paper Tigers", tagline="Fake it till the empire falls.",
        synopsis="Two broke cousins bluff their way into running a struggling family newspaper and accidentally break the story of the decade.",
        year=2024, runtime_min=88, maturity="TV-14", genres=["Comedy", "Drama"],
        moods=["comfort", "heartfelt"], vibe_tags=["witty", "underdog", "warm", "newsroom"],
        rating=7.5, accent="#A0E34D", gradient=["#243a06", "#A0E34D", "#0A0A0A"],
        badges=[], trending_score=75.8, content_type=T,
        languages=["English", "Hindi"], ott=["StreamBox"], qualities=_q(("480p", 100), ("720p", 230), ("1080p", 800))),
]


def seed_titles() -> list[Title]:
    """Return the curated seed catalog."""
    return list(_SEED)
